# spring.application.name=reliefcamps

# server.port=7030

# # MySQL Configuration
# spring.datasource.url=jdbc:mysql://localhost:3306/myappdb
# spring.datasource.username=root
# spring.datasource.password=root
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# # JPA Configuration
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring:
  application:
    name: reliefcamps
  datasource:
    url: jdbc:mysql://localhost:3306/myappdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 7030

eureka:
  client:
    registerWithEureka: true # Registers this service with the Eureka server
    fetchRegistry: true # Fetches the registry from the Eureka server
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL of the Eureka server to connect with
  instance:
    hostname: localhost # The hostname of the instance
    instance-id: "${spring.application.name}:${instanceId:${random.value}}" # Instance ID, with dynamic values
