# ---
# server:
#   port: 8000
# spring:
#   application:
#     name: gateway-auth
#   datasource:
#     url: jdbc:mysql://localhost:3306/myappdb
#     username: root
#     password: root
#     driver-class-name: com.mysql.cj.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#   cloud:
#     gateway:
#       routes:
#         - id: support-service
#           uri: http://localhost:7010
#           predicates:
#             - Path=/api/helplines/**
# jwt:
#   secret: q5zFJkQ/PWrt8WkWX8h8MfBtkFlw3OtEzyKzB5oA4zY=
spring:
  application:
    name: gateway-auth

  datasource:
    url: jdbc:mysql://localhost:3306/myappdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # Consider changing to 'validate' or 'none' in production
    show-sql: true

  cloud:
    gateway:
      mvc:
        routes:
          - id: support-service
            uri: http://localhost:7010
            predicates:
              - Path=/api/helplines/**

          - id: relief-camps
            uri: http://localhost:7030
            predicates:
              - Path=/api/relief-camps/**
          - id: ircommom
            uri: http://localhost:7020
            predicates:
              - Path=/api/incidents/**
          - id: iranonymous
            uri: http://localhost:7040
            predicates:
              - Path=/api/reports/**
          - id: mapsbackend
            uri: http://localhost:9099
            predicates:
              - Path=/api/location/**

    discovery:
      enabled: true

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

      instance:
        hostname: localhost
        instance-id: ${spring.application.name}:${instanceId:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8000

#logging:
#  level:
#    org.springframework: DEBUG

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000
