# spring.application.name=mapsbackend
# server.port=9099

server:
  port: 9099

spring:
  application:
    name: mapsbackend

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
