# spring.application.name=support
# server.port=7010
# spring.datasource.url=jdbc:mysql://localhost:3306/myappdb
# spring.datasource.username=root
# spring.datasource.password=root
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

server:
  port: 7010

spring:
  application:
    name: support
  datasource:
    url: jdbc:mysql://localhost:3306/myappdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
