# spring.application.name=iranonymous

# server.port=7040
# spring.datasource.url=jdbc:mysql://localhost:3306/myappdb
# spring.datasource.username=root
# spring.datasource.password=root
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

server:
  port: 7040

spring:
  application:
    name: iranonymous
  datasource:
    url: jdbc:mysql://localhost:3306/myappdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
